# Daily Task Sequencing
## It is important to daily sample each task space (8 in total) for each rat we run in the cohort. An example is shown below for a daily experimental block. Rats are run 1-6 on the set task, given by the task generator. Rats are allowed to reach until either a success threshold is reached (num_successes) or a trial threshold is reached. The trial is then terminated, the rat removed, a new rat set inside to take its place, and a new trial (with the correct task type loaded) is initiated using the ReachMaster system.

In [16]:
import numpy as np
import random
import matplotlib.pyplot as plt
import pdb
%matplotlib qt 


n_days = 5 # 5 days a week, can adjust


n_weeks = 2


### 480 seconds of recording per block (8 Hours) ####



n_rats = 6 # 10 minute blocks per rat, 3-4 per day

n_trial_types_range = 4 # 0 (0D), 1,2,3 (1-D x, y, and z), 4, 5 6 (2-D X-Y, X-Z, Y-Z), 7 (3-D)



n_trial_block = n_trial_types_range * n_rats

# I want 5 arrays of [4,6] randomized non-repeating



def get_rnd_int_sample(iv,nrats):
    trial_list=[]
    for i in range(0,nrats):
        #trial_list.append(np.random.shuffle(np.arange(8)))
        trial_list.append(np.random.choice(iv,iv,replace=False))# get randint over 1-8 non-repeatin
                
    #trial_list.reshape(nrats,iv)
    return trial_list

tl=np.asarray(get_rnd_int_sample(4,6))



#### Visualize an experimental day ####

### X is Rat (1-6)

### Y is Type of Experiment (0-8)

rat_range=np.arange(n_rats)
fig1=plt.figure(figsize=(18,18))
f1=fig1.add_subplot(211)
f1.scatter(rat_range,tl[:,0],s=200,label='Session 1 Trials') 
f1.scatter(rat_range,tl[:,1],s=200,label='Session 2 Trials')
f1.scatter(rat_range,tl[:,2],s=200,label='Session 3 Trials')
f1.scatter(rat_range,tl[:,3],s=200,label='Session 4 Trials')
#f1.scatter(rat_range,tl[:,4],s=200,color='k',label='Session 5 Trials')
#f1.scatter(rat_range,tl[:,5],s=200, color='y',label='Session 6 Trials')
f1.set_xticks(rat_range)
f1.set_xticklabels(['Rat 1','Rat 2','Rat 3','Rat 4','Rat 5','Rat 6'])
f1.set_yticks(np.arange(4))
f1.set_yticklabels(['0-D','1-D', '2-D','3-D'])
plt.title('Trial Structure Example Across A Half-Day')
plt.legend(['0-D','1-D', '2-D','3-D'])
plt.savefig('Daily_Experiment_Structure_Example.png')


--Return--
None
> <ipython-input-16-0096c40221f3>(39)<module>()
     37     return trial_list
     38 
---> 39 pdb.set_trace()
     40 tl=np.asarray(get_rnd_int_sample(4,6))
     41 

ipdb> c


## Each day can be thought of as an seperate experiment. Each day of experiments, we have the rat behave in every possible task space. This means 8 sessions per rat. 
## We can also ask that trials not be repeated between each session, however I will single house the animals during data collection to limit the need for this paradigm due to animal communication. 
## Heats should be run 5 days a week at minimum. 

In [2]:
print(tl)

# 0 (0D), 1,2,3 (1-D x, y, and z), 4, 5 6 (2-D X-Y, X-Z, Y-Z), 7 (3-D)

# Rat X Trial Type

# Array is an example of a single day per trial



[[4 3 7 2 5 0 6 1]
 [2 5 6 0 4 3 1 7]
 [5 6 0 4 1 7 2 3]
 [2 4 3 0 6 7 1 5]
 [7 2 4 0 5 6 1 3]
 [4 6 1 2 5 7 0 3]]


## Isotropic hole, cue dimensions (show handle, audio cue), vary daily session time from 5-15 mins (5,10,15), run same amt of trials, check saturation etc.