In [1]:
import pickle
from Analysis_Utils import preprocessing_df as preprocessing
from Analysis_Utils import query_df
import DataStream_Vis_Utils as utils
import Classification_Utils as CU
import pandas as pd
import pdb
import matplotlib.pyplot as plt
import seaborn as sns
from Classification_Visualization import visualize_models
import numpy as np
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression, SGDClassifier
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier, RandomForestClassifier

from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC, NuSVC, SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

%matplotlib qt

def import_robot_data(df_path):
    df=pd.read_pickle(df_path)
    df = preprocessing(df)
    return df

df = import_robot_data('default_save_new_rightsample.pickle')
hdf = df.reset_index(drop=True)
d=pd.read_hdf('RM16_kinematics.h5')



No handles with labels found to put in legend.


In [2]:

nl1=[
 [1,0,0,1,1,'l','Tug',0,0],#single left rew tug
 [2,0,0,1,1,'l','Tug',0,0], # single left rew tug
[3,0,0,1,1,'rla','noTug',0,0],# rl assist, 1 , notug, rew
 [4,0,0,1,1,'l','noTug',0,0], #l single rew notug
 [5,0,0,1,2,'l','noTug',0,0], # l 2 rew no tug
 [6,0,0,1,2,'lra','Tug',0,0], # lra 2 rew tug
 [7,0,0,1,4,'lra','noTug',0,0],# lra 4 rew notug
 [8,0,0,1,1,'lra','noTug',0,0], # lra 1 rew notug
 [9,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
 [10,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
 [11,0,0,1,1,'lra','Tug',0,0],# lra 2 rew tug
 [12,0,0,1,3,'lra','Tug',0,0], # lra 3 rew tug
 [13,0,0,1,3,'lra','Tug',0,0],# lra 3 rew tug
 [14,0,0,1,1,'bi','Tug',0,0], # bi 1 rew tug
 [15,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
 [16,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
[17,0,0,1,1,'lra','Tug',0,0], #lra 1 rew tug
 [19,0,0,1,2,'bi','Tug',0,0],# bi 2 rew tug
[20,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [21,0,0,1,1,'bi','Tug',0,0], # bi 1 r t
 [22,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [23,0,0,1,1,'lra','Tug',0,0], # lra 1 r t
 [24,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [25,0,0,1,1,'lra','Tug',0,0], # lr 1 r t 
 [26,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [18, 0, 0,1,1,'lra','Tug',0,0], # lr 1 r t
 [0,0,0,1,2,'rla','Tug',1,0] # rl 2 r t hand switch

]

l18=[
[1,0,0,1,1,'l','noTug',0,0], # l 1 rew notug
[2,0,0,1,3,'l','noTug',0,0], # l 3 rew notug
[4,0,0,1,3,'lr','noTug',1,0], # lr 3 switching rew notug
[5,0,0,1,1,'l','noTug',0,0], # l 1 rew no tug
[6,0,0,1,1,'l','noTug',0,0], # l 1 rew no tug
[7,0,0,1,2,'lra','noTug',0,0], # lr 2 rew notug
[9,0,0,1,1,'l','noTug',0,0], # l 1 rew notug (check b4)
[10,0,0,1,1,'lra','noTug',0,0], # lr 1 rew notug
[12,0,0,1,1,'lr','noTug',0,0], # lr 1 rew notug
[14,0,0,1,1,'lr','Tug',0,0], # lr 1 rew tug
[15,0,0,1,1,'l','noTug',0,0], # l 1 rew notug
[17,0,0,1,1,'lra','noTug',0,0], # lr 1 rew notug
[0,0,0,1,4,'l','noTug',0,0], # l 4 norew notug
[3,0,0,1,4,'lra','noTug',1,0], # lr 4 switching norew notug
[8,0,0,1,11,'lra','noTug',1,0], # lr 11 switching norew notug
[11,0,0,1,7,'l','noTug',0,0], # l 7 norew notug
[13,0,0,1,7,'l','noTug',0,0], # l 7 norew notug
[16,0,0,1,2,'l','noTug',0,0], # l 2 norew notug
[18,0,0,1,6,'l','noTug',0,0]
]

nl2=[
 [1,0,0,1,1,'l','noTug',0,0], # l 1 rew notug
 [2,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [3,0,0,1,2,'lra','Tug',0,0], # lr 2 rew tug
 [4,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [5,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [6,0,0,1,2,'lra','Tug',0,0], # lr 2 rew tug
 [7,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [8,0,0,1,2,'l','Tug',0,0], # l 2 rew tug
 [9,0,0,1,3,'l','Tug',0,0], # l 3 rew tug
 [10,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [11,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [12,0,0,1,2,'lra','noTug',0,0], # lr 2 rew nt
 [13,0,0,1,2,'lra','noTug',0,0], # lr 2 rew nt
 [14,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [15,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [16,0,0,1,1,'lra','noTug',0,0], # lr 1 rew nt
 [17,0,0,1,1,'l','noTug',0,0], # l 1 rew nt
 [18,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [19,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [20,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [21,0,0,1,1,'lra','Tug',0,0], # lr 1 rew t
 [22,0,0,1,1,'lra','Tug',0,0], # lr 1 rew t
 [23,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [24,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [25,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [26,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [27,0,0,1,1,'l','Tug',0,0], # lr 1 rew t
 [28,0,0,1,6,'lra','noTug',1,0], # lr 6 handswitch rew nt
 [30,0,0,1,15,'lra','Tug',0,0], # lr 15 rew t
 [31,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [32,0,0,1,1,'l','noTug',0,0], # l 1 rew nt
 [33,0,0,1,1,'lra','noTug',0,0], # lr 1 rew nt
 [34,0,0,1,3,'l','Tug',0,0], # l 3 rew t
 [35,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [36,0,0,1,3,'l','Tug',0,0], # l 3 rew t
 [0,0,0,1,1,'lra','Tug',0,0], # lr 1 rew t
 [29,0,0,1,3,'l','noTug',0,0], # l 3 nr nt
 [37,0,0,1,1,'l','Tug',0,0], # l 1 r t
]


### Data Cell ###
blist1=[
[1,1,1,4,1, 'l', 'Tug', 0,0] # succ tugg, left hand, single reach, 
,[2,1,1,3,1,'l','noTug',0,0 ] # left handed reach, no tug of war, 1 reach, no switch, 
,[3,1,1,3,2,'bi',0,1,0]
,[4,1,1,4,1,'l','Tug',0,0] # tries to grab handle when moving
,[6,1,1,3,1,'l','Tug',0,0] # reaching after handle moves but can't grasp
,[7,1,1,2,2,'l',0,0,0] # A mis-label!!
,[8,1,1,3,1,'l','noTug',0,0]
,[10,1,1,3,2,'l','Tug',0,0]
,[17,1,1,4,1,'l','Tug',0,0] # 
,[18,1,1,3,2,'lbi', 'noTug',1,0] # added lbi for multiple reaching arms
,[19,1,1,3,2,'lbi','noTug',1,0] # lbi
,[20,1,1,4,3,'l','Tug',0,0]
,[21,1,1,4,2,'lbi','Tug',0,0]
,[22,1,1,3,1,'l','noTug',0,0]
,[23,1,1,3,1,'l','noTug',0,0]
,[24,1,1,3,2,'lbi','noTug',0,0]
,[25,1,1,2,4,'l',0,0,0]
,[26,1,1,3,3,'lbi','noTug',1,0]
,[27,1,1,4,1,'lbi','Tug',0,0]
,[28,1,1,3,2,'l','noTug',0,0]
,[30,1,1,3,2,'l','noTug',0,0]
,[31,1,1,3,2,'lbi','noTug',0,0]
,[32,1,1,2,4,'l',0,0,0]
,[33,1,1,4,2,'lr','noTug',1,0]
,[34,1,1,3,1,'lbi','noTug',0,0]
,[35,1,1,3,1,'l','noTug',0,0]
,[37,1,1,4,1,'lbi','Tug',0,0]
,[38,1,1,3,2,'lbi','noTug',0,0]
,[39,1,1,3,3,'l','noTug',0,0]
,[40,1,1,3,1,'l','noTug',0,0]
,[43,1,1,3,1,'bi','noTug',0,0]
,[44,1,1,4,2,'lbi','Tug',0,0]
,[45,1,1,3,1,'lbi','noTug',0,0]
,[46,1,1,3,1,'lbi','noTug',0,0]
,[47,1,1,3,1,'lbi','noTug',0,0]
,[48,1,1,3,2,'lbi','Tug',0,0]
,[0,1,1,0,0,0,0,0,0]
,[5,1,1,2,4,'lr',0,0,0]
,[9,1,1,1,3,'l',0,0,0]
,[11,1,1,1,1,'l',0,0,0]
,[12,1,1,1,1,'l',0,0,0]
,[13,1,1,1,1,'l',0,0,0]
,[14,1,1,1,1,'l',0,0,0]
,[15,1,1,1,1,'l',0,0,0]
,[16,1,1,0,0,0,0,0,0]
,[29,1,1,1,4,'l',0,0,0]
,[36,1,1,1,9,'llr','Tug',1,0] # lots of stuff going on here
,[41,1,1,1,6,'l',0,0,0]
,[42,1,1,1,8,'llr','Tug',1,0]
,[49,1,1,2,4,'lr',0,0,0]]


elist = [
 [0, 1723, 2284, 0, 0, 0, 'no_tug', 0, 4] # null
, [1, 5593, 6156, 0, 0, 0, 'no_tug', 0, 3] # null
, [2, 7866, 8441, 3, 2, 'l', 'no_tug', 0, 10]
, [3, 8873, 9426, 1, 7, 'l', 'no_tug', 0, 20]
,[4, 10101, 10665, 1, 3, 'l', 'no_tug', 0, 15]
, [5, 12962, 13524, 1, 8, 'l', 'no_tug', 0, 27]
, [6, 14760, 15351, 3, 2, 'bi', 'no_tug', 1, 5] ## bi
, [7, 15802, 16431, 3, 4, 'l', 'no_tug', 1, 8]
,[8, 17400, 17964, 1, 3, 'l', 'no_tug', 0, 7]
, [9, 18923, 19485, 3, 4, 'l', 'no_tug', 0, 6]
, [10, 20044, 20604, 1, 5, 'l', 'no_tug', 0, 6] 
, [11, 24406, 24969, 1, 1, 'l', 'no_tug', 0, 6]
, [12, 26962, 27521, 3, 1, 'l', 'no_tug', 0, 5]
, [13, 27980, 28536, 1, 12, 'l', 'no_tug', 0, 18]
, [14, 29034, 29596, 3, 9, 'l', 'no_tug', 1, 13] 
, [15, 30106, 30665, 3, 1, 'l', 'no_tug', 0, 1]
, [16, 38998, 39591, 1, 2, 'l', 'no_tug', 0, 4]
,[17, 40033, 40594, 0, 0, 0, 'no_tug', 0, 2]
, [18, 45355, 45914, 3, 7, 'l', 'no_tug', 0, 6]
,[19, 46845, 47405, 3, 2, 'l', 'no_tug', 1, 7]
,[20, 50359, 50949, 3, 2, 'l', 'no_tug', 1, 3]
, [21, 58229, 58793, 3, 5, 'l', 'no_tug', 0, 2]
,[22, 59596, 60427, 3, 2, 'l', 'no_tug', 0, 3]
, [23, 60903, 61466, 3, 1, 'l', 'no_tug', 0, 4]
, [24, 62233, 62790, 3, 2, 'l', 'no_tug', 0, 4]
, [25, 66026, 66600, 1, 9, 'l', 'no_tug', 0, 7] # classifed as success in py notebook, but is failed trial
,  [26, 67473, 68046, 3, 2, 'l', 'no_tug', 1, 2]
,  [27, 68689, 69260, 3, 2, 'l', 'no_tug', 1, 3]
,  [28, 70046, 70617, 3, 2, 'l', 'no_tug', 1, 5]

, [29, 71050, 71622, 3, 11, 'l', 'no_tug', 1, 7]
, [30, 72914, 73501, 3, 1, 'l', 'no_tug', 0, 1]
, [31, 74777, 75368, 3, 3, 'l', 'no_tug', 1, 4]
, [32, 81538, 82106, 3, 9, 'l', 'no_tug', 1, 7]
, [33, 82534, 83114, 3, 4, 'bi', 'no_tug', 1, 3] ## bi
, [34, 83546, 84118, 3, 2, 'l', 'no_tug', 1, 1]
, [35, 85563, 86134, 3, 2, 'l', 'no_tug', 1, 2]
,[36, 86564, 87134, 1, 13, 'l', 'no_tug', 0, 5] # fail
, [37, 87574, 88173, 3, 7, 'l', 'no_tug', 0, 8]
, [38, 89012, 89584, 3, 4, 'bi', 'no_tug', 1, 5] ## bi

, [39, 90738, 91390, 3, 7, 'l', 'no_tug', 1, 2]
, [40, 91818, 92387, 1, 7, 'l', 'no_tug', 0, 6] # fail
]

elists,ev= CU.make_vectorized_labels(elist)
labellist,dddd= CU.make_vectorized_labels(blist1)
nl1lists,ev1 = CU.make_vectorized_labels(nl1)
nl2lists,ev2 = CU.make_vectorized_labels(nl2)
l18l, ev18 = CU.make_vectorized_labels(l18)

et=0
el=0
# windowsize call = 800 atm
hot_vector, tt, feats, e = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','20','0190920','S3',9,window_length=800,pre=100)



C:\Users\bassp\OneDrive\Desktop\Classification_Utils.py:317: FutureWarning: in the future negative indices will not be ignored by `numpy.delete`.
  np.delete(lick_mask_array, [-1])


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. .

In [3]:
tt.shape

(50, 3, 27, 900)

In [9]:
## Use N Prediction to Segment in Kinematic Datastream

# Function
# Ruptures: Create model, input, output, viz
# Input from classifier : Predicted_N
# Compare to: Non-Predicted_N
# We want to do this analysis on basically the kinematic data stream of [12:72] (get all arm data)
# 
import Segmentation_Utils as SU
import ruptures as rpt
def arm_vector_from_kinematics(tka):
    # shape of [N, 27,3, Win
    tz=tka[:,:,3:15,:]
    return tz

arms = arm_vector_from_kinematics(tt)


import h5py

with h5py.File('RM16_920_S3.h5', 'w') as hf:
    hf.create_dataset("timeseries",  data=arms)
    hf.create_dataset("labels",data=blist1)

# save arms and blist to avoid memory error
trial_seg=[]




In [ ]:
for ix in range(0,arms.shape[0]):
    # draw pred backpts from the labels to see how well ruptures does
    
    trial_seg.append(SU.segment_time_series(arms[ix,:,:,:].reshape(arms.shape[1]*arms.shape[2]*arms.shape[3]),
                                            bkps=blist1[ix][4]))
    print(ix)



