## We will use this workflow to investigate catagorical supervised machine learning for our behavioral annotations.
## The goal is to achieve maximal classification in each decision category. Any means may be used (we care about predictive accuracy). 

In [1]:
import pickle
from Analysis_Utils import preprocessing_df as preprocessing
from Analysis_Utils import query_df
import DataStream_Vis_Utils as utils
import Classification_Utils as CU
import pandas as pd
import pdb
import matplotlib.pyplot as plt
import seaborn as sns
from Classification_Visualization import visualize_models
import numpy as np
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression, SGDClassifier
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier, RandomForestClassifier

from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC, NuSVC, SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

%matplotlib qt

def import_robot_data(df_path):
    df=pd.read_pickle(df_path)
    df = preprocessing(df)
    return df

df = import_robot_data('default_save_new_rightsample.pickle')
hdf = df.reset_index(drop=True)
d=pd.read_hdf('RM16_kinematics.h5')


No handles with labels found to put in legend.


In [ ]:
d14=pd.read_hdf('kinematic_data_save_df_RM14.h5')

dd_1 = utils.get_single_trial(hdf,'20','S4','RM15')
dd_1 = dd_1.reset_index(drop=True)

In [3]:
dd_1['SF'].values

array([array([ 2,  3,  9, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 26, 30,
       33, 34, 35, 36, 38, 39, 41, 42, 43, 45, 46, 48], dtype=int64)],
      dtype=object)

In [4]:
import numpy as np
d.index.levels

FrozenList([['RM16'], ['0190917', '0190918', '0190919', '0190920', '0190925', '0190926', '0190927', '0190928'], ['S1', 'S2', 'S3', 'S4'], [0]])

In [5]:
hot_vectornl15, ttnl15, featsnl15, enl15 = CU.make_s_f_trial_arrays_from_block(d14,hdf,et,el,'RM14','26','0190926','S2',9)

NameError: name 'et' is not defined

In [ ]:
et =0
el = 0
hot_vector, tt, feats, e = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','18','0190918','S1',9)

In [2]:
nl1=[
 [1,0,0,1,1,'l','Tug',0,0],#single left rew tug
 [2,0,0,1,1,'l','Tug',0,0], # single left rew tug
[3,0,0,1,1,'rla','noTug',0,0],# rl assist, 1 , notug, rew
 [4,0,0,1,1,'l','noTug',0,0], #l single rew notug
 [5,0,0,1,2,'l','noTug',0,0], # l 2 rew no tug
 [6,0,0,1,2,'lra','Tug',0,0], # lra 2 rew tug
 [7,0,0,1,4,'lra','noTug',0,0],# lra 4 rew notug
 [8,0,0,1,1,'lra','noTug',0,0], # lra 1 rew notug
 [9,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
 [10,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
 [11,0,0,1,1,'lra','Tug',0,0],# lra 2 rew tug
 [12,0,0,1,3,'lra','Tug',0,0], # lra 3 rew tug
 [13,0,0,1,3,'lra','Tug',0,0],# lra 3 rew tug
 [14,0,0,1,1,'bi','Tug',0,0], # bi 1 rew tug
 [15,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
 [16,0,0,1,1,'l','Tug',0,0], # l 1 rew tug
[17,0,0,1,1,'lra','Tug',0,0], #lra 1 rew tug
 [19,0,0,1,2,'bi','Tug',0,0],# bi 2 rew tug
[20,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [21,0,0,1,1,'bi','Tug',0,0], # bi 1 r t
 [22,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [23,0,0,1,1,'lra','Tug',0,0], # lra 1 r t
 [24,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [25,0,0,1,1,'lra','Tug',0,0], # lr 1 r t 
 [26,0,0,1,1,'l','Tug',0,0], # l 1 r t
 [18, 0, 0,1,1,'lra','Tug',0,0], # lr 1 r t
 [0,0,0,1,2,'rla','Tug',1,0] # rl 2 r t hand switch

]

l18=[
[1,0,0,1,1,'l','noTug',0,0], # l 1 rew notug
[2,0,0,1,3,'l','noTug',0,0], # l 3 rew notug
[4,0,0,1,3,'lr','noTug',1,0], # lr 3 switching rew notug
[5,0,0,1,1,'l','noTug',0,0], # l 1 rew no tug
[6,0,0,1,1,'l','noTug',0,0], # l 1 rew no tug
[7,0,0,1,2,'lra','noTug',0,0], # lr 2 rew notug
[9,0,0,1,1,'l','noTug',0,0], # l 1 rew notug (check b4)
[10,0,0,1,1,'lra','noTug',0,0], # lr 1 rew notug
[12,0,0,1,1,'lr','noTug',0,0], # lr 1 rew notug
[14,0,0,1,1,'lr','Tug',0,0], # lr 1 rew tug
[15,0,0,1,1,'l','noTug',0,0], # l 1 rew notug
[17,0,0,1,1,'lra','noTug',0,0], # lr 1 rew notug
[0,0,0,1,4,'l','noTug',0,0], # l 4 norew notug
[3,0,0,1,4,'lra','noTug',1,0], # lr 4 switching norew notug
[8,0,0,1,11,'lra','noTug',1,0], # lr 11 switching norew notug
[11,0,0,1,7,'l','noTug',0,0], # l 7 norew notug
[13,0,0,1,7,'l','noTug',0,0], # l 7 norew notug
[16,0,0,1,2,'l','noTug',0,0], # l 2 norew notug
[18,0,0,1,6,'l','noTug',0,0]
]

nl2=[
 [1,0,0,1,1,'l','noTug',0,0], # l 1 rew notug
 [2,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [3,0,0,1,2,'lra','Tug',0,0], # lr 2 rew tug
 [4,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [5,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [6,0,0,1,2,'lra','Tug',0,0], # lr 2 rew tug
 [7,0,0,1,1,'lra','Tug',0,0], # lr 1 rew tug
 [8,0,0,1,2,'l','Tug',0,0], # l 2 rew tug
 [9,0,0,1,3,'l','Tug',0,0], # l 3 rew tug
 [10,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [11,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [12,0,0,1,2,'lra','noTug',0,0], # lr 2 rew nt
 [13,0,0,1,2,'lra','noTug',0,0], # lr 2 rew nt
 [14,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [15,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [16,0,0,1,1,'lra','noTug',0,0], # lr 1 rew nt
 [17,0,0,1,1,'l','noTug',0,0], # l 1 rew nt
 [18,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [19,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [20,0,0,1,2,'l','noTug',0,0], # l 2 rew nt
 [21,0,0,1,1,'lra','Tug',0,0], # lr 1 rew t
 [22,0,0,1,1,'lra','Tug',0,0], # lr 1 rew t
 [23,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [24,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [25,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [26,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [27,0,0,1,1,'l','Tug',0,0], # lr 1 rew t
 [28,0,0,1,6,'lra','noTug',1,0], # lr 6 handswitch rew nt
 [30,0,0,1,15,'lra','Tug',0,0], # lr 15 rew t
 [31,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [32,0,0,1,1,'l','noTug',0,0], # l 1 rew nt
 [33,0,0,1,1,'lra','noTug',0,0], # lr 1 rew nt
 [34,0,0,1,3,'l','Tug',0,0], # l 3 rew t
 [35,0,0,1,1,'l','Tug',0,0], # l 1 rew t
 [36,0,0,1,3,'l','Tug',0,0], # l 3 rew t
 [0,0,0,1,1,'lra','Tug',0,0], # lr 1 rew t
 [29,0,0,1,3,'l','noTug',0,0], # l 3 nr nt
 [37,0,0,1,1,'l','Tug',0,0], # l 1 r t
]


### Data Cell ###
blist1=[
[1,1,1,4,1, 'l', 'Tug', 0,0] # succ tugg, left hand, single reach, 
,[2,1,1,3,1,'l','noTug',0,0 ] # left handed reach, no tug of war, 1 reach, no switch, 
,[3,1,1,3,2,'bi',0,1,0]
,[4,1,1,4,1,'l','Tug',0,0] # tries to grab handle when moving
,[6,1,1,3,1,'l','Tug',0,0] # reaching after handle moves but can't grasp
,[7,1,1,2,2,'l',0,0,0] # A mis-label!!
,[8,1,1,3,1,'l','noTug',0,0]
,[10,1,1,3,2,'l','Tug',0,0]
,[17,1,1,4,1,'l','Tug',0,0] # 
,[18,1,1,3,2,'lbi', 'noTug',1,0] # added lbi for multiple reaching arms
,[19,1,1,3,2,'lbi','noTug',1,0] # lbi
,[20,1,1,4,3,'l','Tug',0,0]
,[21,1,1,4,2,'lbi','Tug',0,0]
,[22,1,1,3,1,'l','noTug',0,0]
,[23,1,1,3,1,'l','noTug',0,0]
,[24,1,1,3,2,'lbi','noTug',0,0]
,[25,1,1,2,4,'l',0,0,0]
,[26,1,1,3,3,'lbi','noTug',1,0]
,[27,1,1,4,1,'lbi','Tug',0,0]
,[28,1,1,3,2,'l','noTug',0,0]
,[30,1,1,3,2,'l','noTug',0,0]
,[31,1,1,3,2,'lbi','noTug',0,0]
,[32,1,1,2,4,'l',0,0,0]
,[33,1,1,4,2,'lr','noTug',1,0]
,[34,1,1,3,1,'lbi','noTug',0,0]
,[35,1,1,3,1,'l','noTug',0,0]
,[37,1,1,4,1,'lbi','Tug',0,0]
,[38,1,1,3,2,'lbi','noTug',0,0]
,[39,1,1,3,3,'l','noTug',0,0]
,[40,1,1,3,1,'l','noTug',0,0]
,[43,1,1,3,1,'bi','noTug',0,0]
,[44,1,1,4,2,'lbi','Tug',0,0]
,[45,1,1,3,1,'lbi','noTug',0,0]
,[46,1,1,3,1,'lbi','noTug',0,0]
,[47,1,1,3,1,'lbi','noTug',0,0]
,[48,1,1,3,2,'lbi','Tug',0,0]
,[0,1,1,0,0,0,0,0,0]
,[5,1,1,2,4,'lr',0,0,0]
,[9,1,1,1,3,'l',0,0,0]
,[11,1,1,1,1,'l',0,0,0]
,[12,1,1,1,1,'l',0,0,0]
,[13,1,1,1,1,'l',0,0,0]
,[14,1,1,1,1,'l',0,0,0]
,[15,1,1,1,1,'l',0,0,0]
,[16,1,1,0,0,0,0,0,0]
,[29,1,1,1,4,'l',0,0,0]
,[36,1,1,1,9,'llr','Tug',1,0] # lots of stuff going on here
,[41,1,1,1,6,'l',0,0,0]
,[42,1,1,1,8,'llr','Tug',1,0]
,[49,1,1,2,4,'lr',0,0,0]]


elist = [
 [0, 1723, 2284, 0, 0, 0, 'no_tug', 0, 4] # null
, [1, 5593, 6156, 0, 0, 0, 'no_tug', 0, 3] # null
, [2, 7866, 8441, 3, 2, 'l', 'no_tug', 0, 10]
, [3, 8873, 9426, 1, 7, 'l', 'no_tug', 0, 20]
,[4, 10101, 10665, 1, 3, 'l', 'no_tug', 0, 15]
, [5, 12962, 13524, 1, 8, 'l', 'no_tug', 0, 27]
, [6, 14760, 15351, 3, 2, 'bi', 'no_tug', 1, 5] ## bi
, [7, 15802, 16431, 3, 4, 'l', 'no_tug', 1, 8]
,[8, 17400, 17964, 1, 3, 'l', 'no_tug', 0, 7]
, [9, 18923, 19485, 3, 4, 'l', 'no_tug', 0, 6]
, [10, 20044, 20604, 1, 5, 'l', 'no_tug', 0, 6] 
, [11, 24406, 24969, 1, 1, 'l', 'no_tug', 0, 6]
, [12, 26962, 27521, 3, 1, 'l', 'no_tug', 0, 5]
, [13, 27980, 28536, 1, 12, 'l', 'no_tug', 0, 18]
, [14, 29034, 29596, 3, 9, 'l', 'no_tug', 1, 13] 
, [15, 30106, 30665, 3, 1, 'l', 'no_tug', 0, 1]
, [16, 38998, 39591, 1, 2, 'l', 'no_tug', 0, 4]
,[17, 40033, 40594, 0, 0, 0, 'no_tug', 0, 2]
, [18, 45355, 45914, 3, 7, 'l', 'no_tug', 0, 6]
,[19, 46845, 47405, 3, 2, 'l', 'no_tug', 1, 7]
,[20, 50359, 50949, 3, 2, 'l', 'no_tug', 1, 3]
, [21, 58229, 58793, 3, 5, 'l', 'no_tug', 0, 2]
,[22, 59596, 60427, 3, 2, 'l', 'no_tug', 0, 3]
, [23, 60903, 61466, 3, 1, 'l', 'no_tug', 0, 4]
, [24, 62233, 62790, 3, 2, 'l', 'no_tug', 0, 4]
, [25, 66026, 66600, 1, 9, 'l', 'no_tug', 0, 7] # classifed as success in py notebook, but is failed trial
,  [26, 67473, 68046, 3, 2, 'l', 'no_tug', 1, 2]
,  [27, 68689, 69260, 3, 2, 'l', 'no_tug', 1, 3]
,  [28, 70046, 70617, 3, 2, 'l', 'no_tug', 1, 5]

, [29, 71050, 71622, 3, 11, 'l', 'no_tug', 1, 7]
, [30, 72914, 73501, 3, 1, 'l', 'no_tug', 0, 1]
, [31, 74777, 75368, 3, 3, 'l', 'no_tug', 1, 4]
, [32, 81538, 82106, 3, 9, 'l', 'no_tug', 1, 7]
, [33, 82534, 83114, 3, 4, 'bi', 'no_tug', 1, 3] ## bi
, [34, 83546, 84118, 3, 2, 'l', 'no_tug', 1, 1]
, [35, 85563, 86134, 3, 2, 'l', 'no_tug', 1, 2]
,[36, 86564, 87134, 1, 13, 'l', 'no_tug', 0, 5] # fail
, [37, 87574, 88173, 3, 7, 'l', 'no_tug', 0, 8]
, [38, 89012, 89584, 3, 4, 'bi', 'no_tug', 1, 5] ## bi

, [39, 90738, 91390, 3, 7, 'l', 'no_tug', 1, 2]
, [40, 91818, 92387, 1, 7, 'l', 'no_tug', 0, 6] # fail
]

elists,ev= CU.make_vectorized_labels(elist)
labellist,dddd= CU.make_vectorized_labels(blist1)
nl1lists,ev1 = CU.make_vectorized_labels(nl1)
nl2lists,ev2 = CU.make_vectorized_labels(nl2)
l18l, ev18 = CU.make_vectorized_labels(l18)

et=0
el=0
# windowsize call = 800 atm
hot_vector, tt, feats, e = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','20','0190920','S3',9,window_length=800,pre=100)
hot_vector3,tt3,feats3, e3 = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','19','0190919','S3',9)# Emily label trial list
hot_vectornl2, ttnl2, featsnl2, enl2 = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','17','0190917','S2',9)
hot_vectornl1, ttnl1, featsnl1, enl1 = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','17','0190917','S1',9)
hot_vectorl18,ttl18,featsl18, el18 = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','18','0190918','S1',9)
#hot_vectorl19,ttl19,featsl19, el19 = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','18','0190918','S1',9)

matched_kin_b1, ez1 = CU.match_stamps(tt,blist1,e) # Matched to blist1
matched_kin_e1, ez4 = CU.match_stamps(tt3, elists,e3) # Matched to blist4
matched_kin_b1nl1, eznl1 = CU.match_stamps(ttnl1,nl1lists,enl1) # Matched to blist1
matched_kin_b1nl2, eznl2 = CU.match_stamps(ttnl2,nl2lists,enl2) # Matched to blist1
matched_kin_e1l18, ezl18 = CU.match_stamps(ttl18, l18l,el18) # Matched to blist4


c = CU.create_ML_array(matched_kin_b1,ez1)
c1 = CU.create_ML_array(matched_kin_e1,ez4)
c2 = CU.create_ML_array(matched_kin_e1l18
                        ,ezl18)
c3 = CU.create_ML_array(matched_kin_b1nl1,eznl1)
c4 = CU.create_ML_array(matched_kin_b1nl2,eznl2)


final_ML_array,final_feature_array = CU.stack_ML_arrays([c,c1,c2,c3,c4],[blist1,elists,l18l,nl1lists,nl2lists])




C:\Users\bassp\OneDrive\Desktop\Classification_Utils.py:317: FutureWarning: in the future negative indices will not be ignored by `numpy.delete`.
  np.delete(lick_mask_array, [-1])


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. .

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. .

In [3]:
import h5py

with h5py.File('ml_array_RM16.h5', 'w') as hf:
    hf.create_dataset("RM16",  data=final_ML_array)
    hf.create_dataset("RM16_labels",data=final_feature_array)


In [ ]:
hot_vectornl1, ttnl1, featsnl1, enl1 = CU.make_s_f_trial_arrays_from_block(d,hdf,et,el,'RM16','17','0190917','S1',9)

In [ ]:
## from sklearn.ensemble import RandomForestClassifier
import matplotlib
#matplotlib.use('TkAgg')
%matplotlib inline

from Classification_Visualization import visualize_models

from sklearn.linear_model import LogisticRegressionCV, LogisticRegression, SGDClassifier
from sklearn.ensemble import BaggingClassifier, ExtraTreesClassifier, RandomForestClassifier

from sklearn.metrics import f1_score
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC, NuSVC, SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

model = RandomForestClassifier(n_estimators=10000,max_depth=2)

predictions = CU.classification_structure(final_ML_array,final_feature_array,model,kFold=5,LOO=False,PCA_data=3,bal=False)



In [5]:
model = RandomForestClassifier(n_estimators=5000,max_depth=2)
predictions = CU.classification_structure(final_ML_array,final_feature_array,model,kFold=5,LOO=False)

# cumulative variance explained -> produce plot for PCA
# LARGE # of PC's!!! 
# Increase WINDOW SIZE!!!!

# Automate pipeline extraction
# Class balances, 
# Classifiers should be run across all data
# Balance Classes

# Heirarchy: N>2? N<2?

# Extend trial by 400 frames , check accuracy!

C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\metrics\_ranking.py:681: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]
C:\Users\bassp\anaconda3\envs\DLC-GPU

C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\metrics\_ranking.py:681: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\metrics\_ranking.py:681: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_inde

C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\metrics\_ranking.py:681: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\

C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will b

C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\tight_layout.py:181: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations. 
  warnings.warn('Tight layout not applied. '
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in ve

C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
C:\Users\bassp\anaconda3\envs\DLC-GPU\lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will b

In [6]:
## Function to:: Strip various features, feature sets (do exp vs kinematic) from ML vector, compare

predictions

# wow really bad now

# re-sample classes, maybe try to classify "which" arm

# ask how many reaches w/ changepoints?

([array([0.94285714, 0.97142857, 0.97142857, 0.97142857, 0.97142857]),
  array([0.45714286, 0.6       , 0.71428571, 0.54285714, 0.4       ]),
  array([0.57142857, 0.6       , 0.8       , 0.85714286, 0.45714286])],
 RandomForestClassifier(max_depth=2, n_estimators=5000))

In [ ]:


models = [
    SVC(gamma='auto'), NuSVC(gamma='auto'), LinearSVC(),
    SGDClassifier(max_iter=100, tol=1e-3), KNeighborsClassifier(),
    LogisticRegression(solver='lbfgs'), LogisticRegressionCV(cv=5),
    BaggingClassifier(), ExtraTreesClassifier(n_estimators=3000),
    RandomForestClassifier(n_estimators=3000)
]



# start grid-searching over these models w/ diff parameters.

pred_array=[]
for model in models:
    for ix in range(1,10):
         pred_array.append(CU.classification_structure(final_ML_array,final_feature_array,model,kFold=5,LOO=False,PCA_data=n,bal=False))
            

# Plot predictions inside of pred array 
n=3
nr = np.linspace(0,len(models))
colors = ['r','g','b','m','y','o','gold','silver','peru']
for i,m in enumerate(models):
    m=str(m) # get label name
    pz=pred_array[i]
    ax=plt.figure()
    ax.plot(nr,pz,c=colors[i],label=m)

In [ ]:
# Segmentation

# c is ML vector, tt is kinematics

# take PC's, segment each trial
from sklearn.decomposition import SparsePCA
from sklearn.decomposition import PCA
transformer = SparsePCA(n_components=3, random_state=0)

cxs=transformer.fit_transform(c.reshape(c.shape[0],c.shape[1]*c.shape[2]))

cxs_kin = transformer.fit_transform(tt.reshape(tt.shape[0],tt.shape[1]*tt.shape[2]*tt.shape[3]))

#for idx in range(0,c.shape[0]):


In [ ]:
cxs_kin.shape # compressed entire feature space into vector



In [ ]:
def trialized_PCA(ml_array,n_comps=3,sparse=False):
    if sparse:
        transformer = SparsePCA(n_components=n_comps, random_state=0)
    else:
        transformer=PCA(n_components=n_comps,random_state=0,whiten=True)
    pdb.set_trace()
    num_trials=ml_array.shape[0]
    nfeats=ml_array.shape[1]
    len_trials=ml_array.shape[2]
    pc_array = np.zeros((num_trials,len_trials,n_comps))
    for xii in range(0,num_trials):
        pc_array[xii,:,:] = transformer.fit_transform(ml_array[xii,:,:].reshape(len_trials,nfeats))
    return pc_array

In [ ]:
pcsx = trialized_PCA(c)
pcsx.shape

In [ ]:
# plot pca 1st 10 trials

ax = plt.figure(figsize=(16,10)).gca(projection='3d')
# Plot PCA for diff exp behaviors
#ck = transformer.transform(cxs_kin)

def plot_PCA(X,color='r',handle=0):
    handle = str(handle+'   trial')
    ax.scatter(X[0, 0], X[0, 1], X[0, 2],c=color,s=400,
           edgecolor='k',label='Start')
    ax.scatter(X[-1, 0], X[-1, 1], X[-1, 2],c=color,s=400,
           edgecolor='k',label='End')
    ax.scatter(X[:, 0], X[:, 1], X[:, 2],c=color,
           edgecolor='k',label=handle)
    ax.plot(X[:, 0], X[:, 1], X[:, 2],c=color,
           label=handle)
    plt.legend()
    plt.title('Trial-To-Trial PCA Projection of Feature Vector (Experiment + Posture)')
#plot_PCA(pcsx[2,:,:])

c_list = ['r','g','b','m','k']

for rfx in range(10,15):
    rr=rfx-10
    plot_PCA(pcsx[rfx],c_list[rr],handle=str(rfx))
    